//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dismissal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dismissal()
        {
            this.Dism_Prod = new HashSet<Dism_Prod>();
        }
    
        public int Dism_Id { get; set; }
        public int Store_Id { get; set; }
        public int Cus_id { get; set; }
        public Nullable<System.DateTime> Dism_date { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dism_Prod> Dism_Prod { get; set; }
        public virtual Store Store { get; set; }
    }
}
