//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliePermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuppliePermission()
        {
            this.Supplied_Prod = new HashSet<Supplied_Prod>();
        }
    
        public int SupPerm_Id { get; set; }
        public Nullable<int> Store_Id { get; set; }
        public Nullable<int> Sup_Id { get; set; }
        public Nullable<System.DateTime> SupPerm_Date { get; set; }
    
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplied_Prod> Supplied_Prod { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
