//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.SuppliePermissions = new HashSet<SuppliePermission>();
        }
    
        public int Sup_Id { get; set; }
        public string Sup_Name { get; set; }
        public string Sup_Phone { get; set; }
        public string Sup_Fax { get; set; }
        public string Sup_Telephone { get; set; }
        public string Sup_Mail { get; set; }
        public string Sup_Site { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliePermission> SuppliePermissions { get; set; }
    }
}
